name: The Study of Robert
favicon: null
layout_spectrum: 0.8923
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8e3318'
    - '#7b2411'
    - '#782d1a'
    - '#a3482d'
    - '#6f1805'
  brandStrength: 0.375
  lightness: 0.4375
  saturation: 0.15039002266712487
  rhythmicContrast: 0.830153692048043
purpose: []
